export const horarioEstudoMatutino = [
  {
    horarioEstudoId:1,
    horarioInicio: "08:00",
    horarioFim: "10:00",
    segunda: "Inglês",
    terca: "Oratória",
    quarta: "Cálculo 1",
    quinta: "Física 1",
    sexta: "Lógica",
    sabado: "",
    domingo: "",
  },
  {
    horarioEstudoId:2,
    horarioInicio: "11:00",
    horarioFim: "12:00",
    segunda: "Lógica",
    terca: "Ingês",
    quarta: "Algebra linear",
    quinta: "Física 1",
    sexta: "",
    sabado: "Física 1",
    domingo: "Física 1",
  },
];
export const horarioEstudoVespertino = [
  {
    horarioEstudoId: 3,
    horarioInicio: "13:00",
    horarioFim: "14:00",
    segunda: "Estatística 1",
    terca: "Vetores",
    quarta: "Física 2",
    quinta: "Física 1",
    sexta: "Lógica",
    sabado: "",
    domingo: "Banco de dados",
  },
  {
    horarioEstudoId: 4,
    horarioInicio: "13:00",
    horarioFim: "14:00",
    segunda: "Estatística 1",
    terca: "Vetores",
    quarta: "Física 2",
    quinta: "Física 1",
    sexta: "Lógica",
    sabado: "",
    domingo: "Banco de dados",
  },
];
export const horarioEstudoNoturno = [
  {
    horarioEstudoId: 5  ,
    horarioInicio: "18:00",
    horarioFim: "20:00",
    segunda: "TCC",
    terca: "Estágio",
    quarta: "Metodologia ",
    quinta: "Física 3",
    sexta: "Web",
    sabado: "Banco de dados",
    domingo: "",
  },
  {
    horarioEstudoId:6   ,
    horarioInicio: "18:00",
    horarioFim: "20:00",
    segunda: "TCC",
    terca: "Estágio",
    quarta: "Metodologia ",
    quinta: "Física 3",
    sexta: "Web",
    sabado: "Banco de dados",
    domingo: "",
  },
];